name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  backend:
    name: CI Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Linter
        run: npm run lint

      - name: Rodar Testes
        run: npm test

      - name: Rodar auditoria de segurança
        run: npm audit

  frontend:
    name: CI Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar Linter
        run: npm run lint

      - name: Rodar Testes
        run: npm test

      - name: Rodar auditoria de segurança
        run: npm audit
