name: CI Pipeline

on: 
  push: 
    branches: [ main ]
  
  pull_request: 
    branches: [ main ]

jobs: 
  continuous-integration: 
    runs-on: ubuntu-latest
    steps: 
       - name: checkout código
         uses: actions/checkout@v3
         
       - name: Setup node.js
         uses: actions/setup-node@v3
         with:
          node-version: '22.15.0'

       - name: Instalar dependências
         run: npm ci

       - name: Rodar o ESlint
         run: npm run lint

       - name: Rodar testes #Por hora não tem nenhum teste para ser realizado.
         run: npm run test

       - name: Rodar auditoria do codigo
         run: npm run audit

       - name: Realizar a build #Simular build, pois ainda não foi implementado Next ou Nest para a build ser realizada.
         run: npm run build

         #O Vercel e o Railway já possuem um deploy automatico ao serem linkados no repositorio do Github. Verificar com o professor se pode deixar assim ou ele deseja o link manual usando o secrets.